from fastapi import APIRouter, Depends, Response, status
from schema.models import ChatHistory, QueryRequest, QueryResponse, ApiResponse
from db.models import User
from services.chat import ChatService
from services.prompt import PromptService
from sqlalchemy.ext.asyncio import AsyncSession
from dependencies.rag import get_rag_pipeline
from core.auth_handler import get_current_user
from db.connect import get_db
from rag import RAGPipeline
from core.logger import logger

user_router = APIRouter(prefix="/users", tags=["Users API"])

@user_router.get('/history', response_model=ApiResponse[list[ChatHistory]], response_model_exclude_none=True)
async def get_history(
        page: int = 1, 
        limit:int = 20, 
        current_user: User = Depends(get_current_user), 
        db: AsyncSession = Depends(get_db)
    ) -> ApiResponse[list[ChatHistory]]:
    
    chat_history = await ChatService.get_user_history(current_user.id, db, page, limit)
    logger.info(f'{len(chat_history)} chat history fetched successfully')
    return ApiResponse(data=chat_history)


@user_router.post('/query', response_model=ApiResponse[QueryResponse], response_model_exclude_none=True)
async def query_response(
        body: QueryRequest, 
        response: Response,
        current_user: User = Depends(get_current_user), 
        db: AsyncSession = Depends(get_db), 
        rag_pipeline: RAGPipeline = Depends(get_rag_pipeline)
    ) -> ApiResponse[QueryResponse]:
    
    prompt = await PromptService.prepare_prompt_with_history(body.query, current_user.id, db)
    
    try: 
        result = await rag_pipeline.query(prompt)
        logger.info('Response successfully generated by RAG')
        
        await ChatService.save_chat(current_user.id, body.query, result, db)
        return ApiResponse(data= QueryResponse(response=result), message="Success")
    except Exception as e:
        logger.warning(f"Error during query: {e}")
        err_message = "Sorry, I couldn't process your request at the moment."
        response.status_code = status.HTTP_400_BAD_REQUEST
        
        return ApiResponse(error= err_message, code=status.HTTP_400_BAD_REQUEST)
    

    